### PR TITLE
Add POT files for translation.

### PR DESCRIPTION
**Pull request by hodgestar**
We need:
- a script for re-generating the .pot files.
- a .pot file for the SMS app.
- a .pot file for the USSD app.

### CODE REVIEW

**Comment by hodgestar** [comment]
Ready for review, @rudigiesler and @KaitCrawford.

**Comment by hodgestar** [comment]
Oops. Some silly bugs. Fixing.

**Comment by hodgestar** [comment]
Actuallly ready for review!

**Comment by rudigiesler** [comment]
:+1:

**Comment by KaitCrawford** [comment]
:+1: ... ... I think

**Pull request merged**
